#!/bin/bash

### BEGIN INIT INFO
# Provides:          jobbox_boot
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start jobbox services at boot
# Description:       Starts the jobbox watchman that uploads pdfs to the server
### END INIT INFO


#	http://werxltd.com/wp/2012/01/05/simple-init-d-script-template/

#   DO THESE COMMANDS OUTSIDE OF A VIRTUALENV
# sudo cp jobbox_boot /etc/init.d/
# sudo update-rc.d jobbox_boot defaults

export AWS_ACCESS_KEY_ID=AKIAIBPZ7TTPXXJWSYNQ
export AWS_SECRET_ACCESS_KEY=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

DAEMON=watchman-make
DAEMONOPTS="-p '*.pdf' --run 'python3.5 ~/jobbox_scripts/upload.py'"

NAME=jobbox_boot
DESC="JobBox boot script"
PIDFILE1=/var/run/jb_anonymous.pid
PIDFILE2=/var/run/jb_jobbox.pid
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
start)
	echo "Starting $NAME..."
    cd /var/spool/cups-pdf/ANONYMOUS
    # `$DAEMON $DAEMONOPTS > /dev/null 2>&1 echo $!`
    `$DAEMON $DAEMONOPTS > /home/pi/watchman_log`
    echo "watchman watching /var/spool/cups-pdf/ANONYMOUS for new PDF files"

    cd /var/spool/cups-pdf/JOBBOX
    `$DAEMON $DAEMONOPTS > /dev/null 2>&1 echo $!`
    echo "watchman watching /var/spool/cups-pdf/JOBBOX for new PDF files"
;;
stop)
    pkill watchman
;;
restart)
  	$0 stop
  	$0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
