#!/bin/bash

### BEGIN INIT INFO
# Provides:          wipi_boot
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start wipi services at boot
# Description:       Starts the wipiServer and the polling script
### END INIT INFO


#	http://werxltd.com/wp/2012/01/05/simple-init-d-script-template/

#   DO THESE COMMANDS OUTSIDE OF A VIRTUALENV
# sudo cp wipi_boot.sh /etc/init.d/
#	starts script at runlevels 3, 4, 5 at low priority and stops it at high priority in 1 and 6
# sudo update-rc.d wipi_boot defaults

DAEMON=gunicorn
DAEMONOPTS="-b 0.0.0.0:8888 autoapp:app"

DAEMON_PATH="/home/pi/wipiServer"

NAME=wipi_boot
DESC="WiPi boot script"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
start)
    sudo /sbin/wpa_supplicant -iwlan1 -c/home/pi/wipiServer/wpa_supplicant.conf -B
	printf "%-50s" "Starting $NAME..."
	cd $DAEMON_PATH
    source ./bin/activate
    source .env	
	PID=`sudo $DAEMON $DAEMONOPTS > /dev/null 2>&1 & echo $!`
	echo "Saving PID" $PID " to " $PIDFILE
        if [ -z $PID ]; then
            printf "%s\n" "Fail"
        else
            echo $PID > $PIDFILE
            printf "%s\n" "Ok"
        fi

	printf "%-50s" "Starting WiPi polling script..."
	cd $DAEMON_PATH
	python3.5 wipi_start.py 2>&1 & echo $1
;;
stop)
        
        cd $DAEMON_PATH
        echo "killing wipi_start"
        pkill wipi_start
        if [ -f $PIDFILE ]; then
        	PID=`cat $PIDFILE`
        	printf "%-50s" "Stopping $NAME with PID $PID"
            sudo kill $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;
restart)
  	$0 stop
  	$0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
