#!/bin/bash
# wipi_boot daemon
# chkconfig: 345 20 80
# description: wipi_boot daemon
# processname: wipi_boot

#	http://werxltd.com/wp/2012/01/05/simple-init-d-script-template/

# sudo cp wipi_boot.sh /etc/init.d/
# sudo update-rc.d wipi_boot defaults

#	starts script at runlevels 3, 4, 5 at low priority and stops it at high priority in 1 and 6
# sudo update-rc.d wipi_boot start 90 3 4 5 . stop 10 1 6 . 

DAEMON=gunicorn
DAEMONOPTS="-b 0.0.0.0:8888 autoapp:app"

DAEMON_PATH="/home/pi/wipiServer"

NAME=wipi_boot
DESC="WiPi boot script"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
start)
	printf "%-50s" "Starting $NAME..."
	cd $DAEMON_PATH
    source ./bin/activate
    source .env	
	PID=`sudo $DAEMON $DAEMONOPTS > /dev/null 2>&1 & echo $!`
	echo "Saving PID" $PID " to " $PIDFILE
        if [ -z $PID ]; then
            printf "%s\n" "Fail"
        else
            echo $PID > $PIDFILE
            printf "%s\n" "Ok"
        fi
;;
stop)
        
        cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
        	PID=`cat $PIDFILE`
        	printf "%-50s" "Stopping $NAME with PID $PID"
            sudo kill $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;
restart)
  	$0 stop
  	$0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
