"""empty message

Revision ID: 6915481baaf4
Revises: 
Create Date: 2017-10-30 11:21:31.028661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6915481baaf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wifi_networks',
    sa.Column('_created', sa.DateTime(), nullable=True),
    sa.Column('_updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('essid', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wifi_networks')
    # ### end Alembic commands ###
